fieldLayouts:
  6cfff2b2-8ba5-402f-9c21-1ddaf511fc07:
    tabs:
      -
        elements:
          -
            fieldUid: b2c51e1a-ef5d-4a48-a6f3-8858d2fb91dc # HTTP Status
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: 'Replace the default error title with one that is more user-friendly. (Titles for errors without custom pages are formatted "_Error ###: <Error Name>_")'
            label: ''
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 8af30969-9993-4bd0-9983-003e5634c274 # Error Message
            instructions: ''
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Base Error Info'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 8390b8f6-4e28-44cd-aa4a-6aa074083c46 # Error Codes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Error Code Overrides'
        sortOrder: 2
handle: httpError
hasTitleField: true
name: 'HTTP Error'
section: 4bbc4374-2874-42b5-837e-3e7ded6ff886 # Error Pages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
