field: 8390b8f6-4e28-44cd-aa4a-6aa074083c46
fieldLayouts:
  8b5ccf90-3d1d-439f-97f3-471bce64ae39:
    tabs:
      -
        elements:
          -
            fieldUid: d8355d36-d3ee-4494-af6a-b09b3fcecaae
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bcfee702-9f82-4ece-8d1b-86b689713f52
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 48298e73-da57-4a43-94d5-99dff6f8354b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 482f7419-6607-4993-ac39-4b81d8113569
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  482f7419-6607-4993-ac39-4b81d8113569:
    contentColumnType: boolean
    fieldGroup: null
    handle: appendOriginalMessage
    instructions: 'Append the original error message after this one.'
    name: 'Append Original Message'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  48298e73-da57-4a43-94d5-99dff6f8354b:
    contentColumnType: text
    fieldGroup: null
    handle: messageOverride
    instructions: 'If left blank, the base error message will be used.'
    name: Message
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Basic.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  bcfee702-9f82-4ece-8d1b-86b689713f52:
    contentColumnType: text
    fieldGroup: null
    handle: titleOverride
    instructions: 'If left blank, the base error title will be used.'
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d8355d36-d3ee-4494-af6a-b09b3fcecaae:
    contentColumnType: integer(10)
    fieldGroup: null
    handle: errorCode
    instructions: ''
    name: 'Error Code'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: '1'
      prefix: ''
      previewCurrency: ''
      previewFormat: decimal
      size: '8'
      suffix: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
handle: override
name: Override
sortOrder: 1
