contentColumnType: text
fieldGroup: a7145a7e-c7c8-49cd-8ce8-22971c1b87ba
handle: altText
instructions: 'Text that is read by screen readers or shown if an image fails to load.'
name: 'Alt Text'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
