columnSuffix: null
contentColumnType: string
fieldGroup: d2f7e89b-4d7d-4548-8549-f4261cc069f4 # Error Pages
handle: errorCodes
instructions: 'To override the base title and/or message for a specific error code, add a block below.'
name: 'Error Codes'
searchable: false
settings:
  contentTable: '{{%matrixcontent_errorcodes}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
