contentColumnType: string
fieldGroup: d2f7e89b-4d7d-4548-8549-f4261cc069f4
handle: httpStatus
instructions: 'The HTTP status code this entry should be used for.'
name: 'HTTP Status'
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - '400 - Bad Request'
        -
          - value
          - '400'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '403 - Forbidden'
        -
          - value
          - '403'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '404 - Not Found'
        -
          - value
          - '404'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '410 - Gone'
        -
          - value
          - '410'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '500 - Internal Server Error'
        -
          - value
          - '500'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '503 - Service Unavailable'
        -
          - value
          - '503'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
